Add workspaces template
InteropIO/templates pull request #2
Opened 2023-10-02 13:17 UTC by gdavidkov

2023-10-03 14:15 UTC, arjunah requested changes

2023-10-03 14:15 UTC, arjunah commented on io-connect-desktop-workspaces/public/index.html
> +    <title>Glue42 Workspaces</title>
io.Connect Workspaces

2023-10-03 14:15 UTC, arjunah commented on io-connect-desktop-workspaces/public/manifest.json
> +  "short_name": "Glue42 Workspaces",
io.Connect Workspaces App

2023-10-03 14:15 UTC, arjunah commented on io-connect-desktop-workspaces/public/manifest.json
> +  "name": "Glue42 Workspaces",
io.Connect Workspaces App

2023-10-04 09:31 UTC, arjunah approved these changes

2023-10-22 18:29 UTC, SvetozarMateev approved these changes

2023-10-23 09:13 UTC, arjunah requested changes

2023-10-23 09:13 UTC, arjunah commented on io-connect-desktop-workspaces/README.md
> +This project provides a starter for React based Workspaces applications in io.Connect Desktop and io.Connect Browser.
Template for creating a custom Workspaces App \[for \*\*io.Connect Desktop**](https://docs.interop.io/desktop/capabilities/windows/workspaces/overview/index.html#extending_workspaces) or \[for \*\*io.Connect Browser**](https://docs.interop.io/browser/capabilities/windows/workspaces/workspaces-app/index.html) projects.

\## Prerequisites

For \*\*io.Connect Desktop** projects, \*\*io.Connect Desktop** 9.0 or newer is required. For \*\*io.Connect Browser** 
 projects, \*\*io.Connect Browser** 3.0 or newer is required.

\## Usage

\- Run \`npm install\` to install all dependencies.
\- Run \`npm run start\` to start the app.
\- For \*\*io.Connect Desktop** projects, copy the \`workspaces.json\` configuration file and replace the existing Workspaces App definition in the \`%LocalAppData%\interop.io\io.Connect Desktop\Desktop\config\apps\` folder. For \*\*io.Connect Browser** projects, see the \[Enabling Workspaces](https://docs.interop.io/browser/capabilities/windows/workspaces/enabling-workspaces/index.html) documentation.
\- Start \*\*io.Connect Desktop** to start using and modifying your Workspaces App.

2023-11-03 09:08 UTC, arjunah approved these changes

2023-11-03 09:42 UTC, merged