Feat/add issue reporting template
InteropIO/templates pull request #6
Opened 2023-10-17 17:16 UTC by galin-iliev

2023-11-03 09:11 UTC, arjunah requested changes

2023-11-03 09:11 UTC, arjunah commented on io-connect-desktop-components/src/components/ChannelSelector/ChannelSelector.tsx
> +import { GlueProvider } from "@glue42/react-hooks";
We have @interopio/react-hooks now

2023-11-03 09:11 UTC, arjunah commented on io-connect-desktop-components/src/components/ChannelSelector/ChannelSelector.tsx
> +import Glue from "@glue42/desktop";
@interopio/desktop

2023-11-03 09:11 UTC, arjunah commented on io-connect-desktop-components/package.json
>      "@glue42/desktop": "^5.23.1",
@interopio/desktop and @interopio/react-hooks

2024-02-19 10:01 UTC, galin-iliev commented
The changes from this pull request are in the following PR as well:
https://github.com/InteropIO/templates/pull/11
I\m closing this one.

2024-02-19 10:01 UTC, closed without merging